# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/taskBd
spring.datasource.username=admin
spring.datasource.password=adminsecret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.mvc.hiddenmethod.filter.enabled=true
